### ISSUE TITLE
У меня не запускается

### ISSUE THREAD

**Issue by Fedor-Lyanguzov** [skabrits/EGE#2]
А все почему? А потому что не могу установить необходимые библиотеки, потому что нет `requirements.txt`. Не могу использовать виртуальное окружение, созданное в MacOS, потому что у меня не MacOS.

1. Создать `.gitignore`
   1. Добавить в него `.idea/`
   1. Добавить в него `venv/`
1. Создать `requirements.txt`, куда записать все необходимые модули

**Comment by skabrits** [comment]
> А все почему? А потому что не могу установить необходимые библиотеки, потому что нет `requirements.txt`. Не могу использовать виртуальное окружение, созданное в MacOS, потому что у меня не MacOS.
> 
> 1. Создать `.gitignore`
>    
>    1. Добавить в него `.idea/`
>    2. Добавить в него `venv/`
> 2. Создать `requirements.txt`, куда записать все необходимые модули

Готово

**Comment by Fedor-Lyanguzov** [comment]
Следует протестировать на чистой установке корректную работу.

**Comment by skabrits** [comment]
> Следует протестировать на чистой установке корректную работу.

Ошибка вышла в курсе корабля:
python -m venv .venv
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named venv

**Comment by Fedor-Lyanguzov** [comment]
> > Следует протестировать на чистой установке корректную работу.
> 
> Ошибка вышла в курсе корабля:
> python -m venv .venv
> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named venv

Это потому, что ваша устаревшая ОС все еще считает питон 2 за `python`. Это не так на остальных 80% компьютеров.

**Comment by skabrits** [comment]
> > > Следует протестировать на чистой установке корректную работу.
> > 
> > 
> > Ошибка вышла в курсе корабля:
> > python -m venv .venv
> > /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named venv
> 
> Это потому, что ваша устаревшая ОС все еще считает питон 2 за `python`. Это не так на остальных 80% компьютеров.

Так и что с этим делать?

**Comment by Fedor-Lyanguzov** [comment]
Использовать `python3` везде, где вы использовали `python`

**Comment by skabrits** [comment]
Готово
