### ISSUE TITLE
Не использовать Python 2

### ISSUE THREAD

**Issue by Fedor-Lyanguzov** [skabrits/EGE#3]
Нигде и никогда больше не использовать Python 2. Ни в коем случае. Нет библиотеки под Python 3? Врети, мало искали. Все еще нет? Перепишите старую, это не трудно, для этого есть автоматизированные скрипты (которые работают в 99% случаев).

**Comment by skabrits** [comment]
А что именно там от 2 питона? Можете, пожалуйста, привести список таких библиотек, или как выяснить на каком питоне библиотека. Просто у меня стоит интерпретатор питон 3.7 и всё работает, так что я не уверен, что могу понять что там из 2 питона

**Comment by Fedor-Lyanguzov** [comment]
https://github.com/skabrits/EGE/tree/master/venv/lib/python2.7/site-packages

**Comment by Fedor-Lyanguzov** [comment]
Из-за того, что вы используете PyCharm для создания и управления проектами, и даже не представляете, каким питоном это все запускается.

**Comment by skabrits** [comment]
окей, я постараюсь исправить проблему

**Comment by skabrits** [comment]
> Из-за того, что вы используете PyCharm для создания и управления проектами, и даже не представляете, каким питоном это все запускается, вы думаете, что запускаете питоном 3.7. А вы попробуйте
> 
> ```
> import sys
> print(sys.version)
> ```

Нет, тут как раз всё нормально: 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)

**Comment by Fedor-Lyanguzov** [comment]
> > Из-за того, что вы используете PyCharm для создания и управления проектами, и даже не представляете, каким питоном это все запускается, вы думаете, что запускаете питоном 3.7. А вы попробуйте
> > ```
> > import sys
> > print(sys.version)
> > ```
> 
> Нет, тут как раз всё нормально: 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)

это вы просто так написали, или вставили в программу и запустили?

**Comment by skabrits** [comment]
> > > Из-за того, что вы используете PyCharm для создания и управления проектами, и даже не представляете, каким питоном это все запускается, вы думаете, что запускаете питоном 3.7. А вы попробуйте
> > > ```
> > > import sys
> > > print(sys.version)
> > > ```
> > 
> > 
> > Нет, тут как раз всё нормально: 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
> 
> это вы просто так написали, или вставили в ту самую вашу программу и запустили?

Обижаете, конечно вставил и запустил
